// js/config.js — runtime configuration (no secrets)
// API keys are intentionally empty here; data is served from cached JSON files
// generated by GitHub Actions. See js/config.js.template for details.
// Keys can also be stored via the Data Quality Dashboard (localStorage).
(function () {
  var stored = {};
  try {
    [
      'CENSUS_API_KEY',
      'FRED_API_KEY',
      'REGRID_API_KEY',
      'BRIDGE_BROWSER_TOKEN',
      'BRIDGE_DATASET'
    ].forEach(function (k) {
      var v = localStorage.getItem('coho_api_' + k);
      if (v) stored[k] = v;
    });
  } catch (_) {}

  window.APP_CONFIG = Object.assign({
    CENSUS_API_KEY:       "",
    FRED_API_KEY:         "",
    REGRID_API_KEY:       "",
    BRIDGE_BROWSER_TOKEN: "",
    BRIDGE_DATASET:       "test", // override via Data Quality Dashboard when real MLS access is granted
    DATA_VERSION:         "2026-03-15",

    // ── Analytics (js/components/analytics.js) ────────────────────────────
    // Without these, analytics is local-only (localStorage debug helper).
    // To enable cross-session population data:
    //
    //   Option A — Plausible Analytics (recommended; privacy-first, no cookies):
    //     ANALYTICS_PROVIDER: "plausible"
    //     ANALYTICS_DOMAIN:   "pggllc.github.io"   ← your GitHub Pages domain
    //
    //   Option B — custom beacon endpoint (Cloudflare Worker, Lambda, etc.):
    //     ANALYTICS_ENDPOINT: "https://your-worker.workers.dev/collect"
    //
    ANALYTICS_PROVIDER:   "",   // "plausible" or ""
    ANALYTICS_DOMAIN:     "",   // required when provider = "plausible"
    ANALYTICS_ENDPOINT:   ""    // required when using a custom beacon endpoint
  }, stored);
}());
