// js/config.js — runtime configuration (no secrets)
// API keys are intentionally empty here; data is served from cached JSON files
// generated by GitHub Actions. See js/config.js.template for details.
window.APP_CONFIG = {
  CENSUS_API_KEY: "",
  FRED_API_KEY: "",
  KASHLI_API_KEY: "",
  DATA_VERSION: "2026-02-27"
};
