/**
 * js/site-search.js — site-wide search (powers search.html).
 *
 * Loads the build-time `search-index.json` (generated by scripts/build-public-site.mjs
 * from every public page's title, description, and headings) and renders ranked matches.
 * Uses window.APP_BASE_PATH (from path-resolver.js) so result links resolve root-absolute
 * and work identically from the root and from /places/ pages. Fully self-contained and
 * guarded — if anything is missing it no-ops rather than throwing.
 */
(function () {
  'use strict';

  var BASE = (window.APP_BASE_PATH || '/');
  var input = document.getElementById('siteSearchInput');
  var results = document.getElementById('siteSearchResults');
  var status = document.getElementById('siteSearchStatus');
  if (!input || !results) return;

  var index = null;

  function escapeHtml(s) {
    return String(s == null ? '' : s).replace(/[&<>"']/g, function (c) {
      return { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c];
    });
  }
  function norm(s) { return String(s || '').toLowerCase(); }

  // Every term must appear somewhere (AND). Title hits outrank headings outrank description;
  // a title prefix match is best.
  function scoreItem(it, terms) {
    var t = norm(it.t), d = norm(it.d), k = norm(it.k), s = 0, titleHit = false;
    for (var i = 0; i < terms.length; i++) {
      var term = terms[i];
      var inT = t.indexOf(term), inK = k.indexOf(term), inD = d.indexOf(term);
      if (inT < 0 && inK < 0 && inD < 0) return 0;
      if (inT === 0) { s += 14; titleHit = true; }
      else if (inT > 0) { s += 9; titleHit = true; }
      if (inK >= 0) s += 4;
      if (inD >= 0) s += 2;
    }
    // The 464 place profiles are near-identical apart from the name. If the query didn't hit the
    // place name (title), it's a topic query — down-weight so the relevant topic/dashboard pages
    // rank above the profiles instead of being buried under them.
    if (!titleHit && /^places\/\d+\.html$/.test(it.u)) s *= 0.25;
    return s;
  }

  function search(q) {
    // Strip punctuation so "Silt, Colorado" → ["silt","colorado"] and "silt" hits the title.
    var terms = norm(q).replace(/[^a-z0-9\s]+/g, ' ').split(/\s+/).filter(Boolean);
    if (!terms.length || !Array.isArray(index)) return [];
    return index
      .map(function (it) { return { it: it, s: scoreItem(it, terms) }; })
      .filter(function (x) { return x.s > 0; })
      .sort(function (a, b) { return b.s - a.s || a.it.t.length - b.it.t.length; })
      .slice(0, 60)
      .map(function (x) { return x.it; });
  }

  function render(q) {
    if (!q.trim()) {
      results.innerHTML = '';
      if (status) status.textContent = index
        ? 'Type to search ' + index.length + ' pages — places, dashboards, guides, and data.'
        : 'Loading search index…';
      return;
    }
    var matches = search(q);
    if (!matches.length) {
      results.innerHTML = '<p class="search-empty">No matches for “' + escapeHtml(q) +
        '”. Try a place name (e.g. <strong>Silt</strong>), a topic (<strong>LIHTC</strong>, ' +
        '<strong>AMI</strong>, <strong>rent burden</strong>), or a page title.</p>';
      if (status) status.textContent = '0 results for “' + q + '”.';
      return;
    }
    if (status) {
      status.textContent = matches.length + (matches.length === 60 ? '+' : '') +
        ' result' + (matches.length === 1 ? '' : 's') + ' for “' + q + '”.';
    }
    results.innerHTML = matches.map(function (it) {
      return '<a class="search-result" href="' + BASE + escapeHtml(it.u) + '">' +
        '<span class="search-result-title">' + escapeHtml(it.t) + '</span>' +
        (it.d ? '<span class="search-result-desc">' + escapeHtml(it.d) + '</span>' : '') +
        '</a>';
    }).join('');
  }

  function getQ() {
    try { return new URLSearchParams(window.location.search).get('q') || ''; }
    catch (e) { return ''; }
  }

  function load() {
    fetch(BASE + 'search-index.json', { cache: 'force-cache' })
      .then(function (r) { return r.ok ? r.json() : []; })
      .then(function (data) { index = Array.isArray(data) ? data : []; render(input.value); })
      .catch(function () { index = []; if (status) status.textContent = 'Search index unavailable.'; });
  }

  var q0 = getQ();
  input.value = q0;
  if (q0) document.title = '“' + q0 + '” — Search · COHO Analytics';
  load();

  var debounce;
  input.addEventListener('input', function () {
    clearTimeout(debounce);
    debounce = setTimeout(function () { render(input.value); }, 90);
  });
  try { input.focus(); } catch (e) { /* ignore */ }
})();
