'use strict';

/**
 * Guard for build-hna-data's push-race recovery (#1613).
 *
 * Several data crons write data/home-snapshot.json, data/_manifest.json and
 * data/manifest.json, so two of them landing minutes apart collide by
 * construction. All three are fully DERIVED, so the correct resolution is to
 * take main's side and rebuild from the merged tree — which the workflow
 * already did, but only for data/manifest.json. The 2026-09-12 scheduled run
 * hit all three and aborted, even though the step regenerates all three a few
 * lines later.
 *
 * The important half of this test is the half that must NOT change: a conflict
 * touching anything outside the derived set still refuses recovery. Silently
 * resolving a real source file would be far worse than a failed run.
 */

const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const ROOT = path.resolve(__dirname, '..');
const WF = fs.readFileSync(path.join(ROOT, '.github/workflows/build-hna-data.yml'), 'utf8');

let failures = 0;
function run(name, fn) {
  try { fn(); console.log('  ✓ ' + name); }
  catch (err) { failures += 1; console.error('  ✗ ' + name + '\n    ' + err.message); }
}

console.log('hna-build-rebase-recovery');

run('the derived set covers every artifact the step rebuilds', () => {
  const m = /derived_artifacts=\(([^)]*)\)/.exec(WF);
  assert.ok(m, 'the derived allow-list must exist');
  const listed = m[1].trim().split(/\s+/);
  for (const p of ['data/home-snapshot.json', 'data/_manifest.json', 'data/manifest.json']) {
    assert.ok(listed.includes(p), p + ' is regenerated by this step and must be recoverable');
  }
  assert.equal(listed.length, 3, 'nothing else belongs in the derived set: ' + listed.join(', '));
});

run('a conflict outside the derived set still fails loudly', () => {
  assert.match(WF, /refusing automatic recovery/,
    'the refusal path must survive — silently resolving a source file is worse than a failed run');
  const refusal = /Rebase conflict includes a non-derived path[\s\S]{0,200}?exit 1/.exec(WF);
  assert.ok(refusal, 'the refusal must exit non-zero');
  assert.match(refusal[0], /printf 'Conflicted path/,
    'and must name the paths so the run is diagnosable');
});

run('recovery regenerates rather than picking a side', () => {
  // Taking either side of a derived file leaves it inconsistent with the tree
  // it describes. The recovery restores from main, rebases, then rebuilds.
  const block = /git rebase --abort[\s\S]*?git add "\$\{derived_artifacts\[@\]\}"/.exec(WF);
  assert.ok(block, 'the recovery block must exist');
  const b = block[0];
  assert.match(b, /git restore --source=origin\/main[\s\S]*derived_artifacts/,
    'stale pre-race versions come from main');
  assert.match(b, /node scripts\/build-home-snapshot\.mjs/, 'home snapshot is rebuilt');
  assert.match(b, /npm run audit:file-manifest/, '_manifest is rebuilt');
  assert.match(b, /python3? scripts\/rebuild_manifest\.py/, 'manifest is rebuilt');
});

run('regeneration runs in the order the build step uses', () => {
  const block = /git rebase --abort[\s\S]*?git add "\$\{derived_artifacts\[@\]\}"/.exec(WF)[0];
  const snapshot = block.indexOf('build-home-snapshot.mjs');
  const under = block.indexOf('audit:file-manifest');
  const manifest = block.indexOf('rebuild_manifest.py');
  // rebuild_manifest.py reads the tree the other two have just written, so
  // running it first would bake in stale byte counts.
  assert.ok(snapshot < under && under < manifest,
    'order must be home-snapshot -> _manifest -> manifest, got ' +
    JSON.stringify({ snapshot, under, manifest }));
});

run('the workflow still parses as YAML with a valid shell body', () => {
  // A guard written in bash inside YAML has two ways to break silently.
  const stepBodies = WF.split('\n').filter((l) => l.includes('derived_artifacts'));
  assert.ok(stepBodies.length >= 4, 'the array is referenced throughout the recovery');
  assert.ok(!/\t/.test(WF), 'no tabs — YAML indentation must stay spaces');
});

if (failures) { console.error('hna-build-rebase-recovery: FAIL'); process.exitCode = 1; }
else console.log('hna-build-rebase-recovery: PASS');
