'use strict';

/**
 * Guard for build-hna-data's push-race recovery (#1613).
 *
 * Several data crons write data/home-snapshot.json, data/_manifest.json and
 * data/manifest.json, so two of them landing minutes apart collide by
 * construction. All three are fully DERIVED, so the correct resolution is to
 * take main's side and rebuild from the merged tree — which the workflow
 * already did, but only for data/manifest.json. The 2026-09-12 scheduled run
 * hit all three and aborted, even though the step regenerates all three a few
 * lines later.
 *
 * The important half of this test is the half that must NOT change: a conflict
 * touching anything outside the derived set still refuses recovery. Silently
 * resolving a real source file would be far worse than a failed run.
 */

const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const ROOT = path.resolve(__dirname, '..');
const WF = fs.readFileSync(path.join(ROOT, '.github/workflows/build-hna-data.yml'), 'utf8');

let failures = 0;
function run(name, fn) {
  try { fn(); console.log('  ✓ ' + name); }
  catch (err) { failures += 1; console.error('  ✗ ' + name + '\n    ' + err.message); }
}

console.log('hna-build-rebase-recovery');

// Everything the "Rebuild homepage snapshot and manifests" step writes. A
// path is derived only if a script in that step regenerates it from the tree;
// nothing hand-edited may ever appear here, because the recovery below takes
// main's side of a conflict on these paths without looking.
const DERIVED = [
  'data/home-snapshot.json',        // scripts/build-home-snapshot.mjs
  'places',                         // scripts/hna/build_place_pages.py (whole directory)
  'data/paper/figures.json',        // npm run paper:build
  'data/paper/model-parameters.json',
  'working-paper.html',
  'methods.html',
  'README.md',                      // scripts/compute-inventory.mjs --write (inventory line)
  'AGENTS.md',
  'data/_manifest.json',            // npm run audit:file-manifest
  'data/manifest.json',             // scripts/rebuild_manifest.py
];

run('the derived set covers every artifact the step rebuilds, and nothing else', () => {
  const m = /derived_artifacts=\(([^)]*)\)/.exec(WF);
  assert.ok(m, 'the derived allow-list must exist');
  const listed = m[1].trim().split(/\s+/);
  for (const p of DERIVED) {
    assert.ok(listed.includes(p), p + ' is regenerated by this step and must be recoverable');
  }
  for (const p of listed) {
    assert.ok(DERIVED.includes(p), p + ' is not regenerated by the step and must not be auto-resolved');
  }
});

run('the commit step stages every derived artifact', () => {
  // #1768: the step rebuilt places/, the paper and the inventory line, then
  // discarded them because `git add` stopped at the manifests. Cron commits
  // get no CI, so main stayed red until the next human PR inherited it.
  const add = /git add ((?:[^\n]*\\\n)*[^\n]*)/.exec(WF.slice(WF.indexOf('- name: Commit and push')));
  assert.ok(add, 'the commit step must stage explicitly');
  const staged = add[1].replace(/\\\n/g, ' ').split(/\s+/);
  for (const p of DERIVED) {
    const covered = staged.includes(p) || staged.some((s) => p.startsWith(s + '/'));
    assert.ok(covered, p + ' is rebuilt by the workflow but never committed');
  }
});

run('a conflicted file inside a derived directory counts as derived', () => {
  assert.match(WF, /\[ "\$\{conflicted#"\$derived"\/\}" != "\$conflicted" \]/,
    'places/<geoid>.html must match the `places` entry by prefix');
});

run('a conflict outside the derived set still fails loudly', () => {
  assert.match(WF, /refusing automatic recovery/,
    'the refusal path must survive — silently resolving a source file is worse than a failed run');
  const refusal = /Rebase conflict includes a non-derived path[\s\S]{0,200}?exit 1/.exec(WF);
  assert.ok(refusal, 'the refusal must exit non-zero');
  assert.match(refusal[0], /printf 'Conflicted path/,
    'and must name the paths so the run is diagnosable');
});

run('recovery regenerates rather than picking a side', () => {
  // Taking either side of a derived file leaves it inconsistent with the tree
  // it describes. The recovery restores from main, rebases, then rebuilds.
  const block = /git rebase --abort[\s\S]*?git add "\$\{derived_artifacts\[@\]\}"/.exec(WF);
  assert.ok(block, 'the recovery block must exist');
  const b = block[0];
  assert.match(b, /git restore --source=origin\/main --staged --worktree "\$\{derived_artifacts\[@\]\}"/,
    'stale pre-race versions come from main');
  assert.match(b, /node scripts\/build-home-snapshot\.mjs/, 'home snapshot is rebuilt');
  assert.match(b, /python3? scripts\/hna\/build_place_pages\.py/, 'place pages are rebuilt');
  assert.match(b, /npm run paper:build/, 'paper figures are rebuilt');
  assert.match(b, /node scripts\/compute-inventory\.mjs --write/, 'inventory line is rebuilt');
  assert.match(b, /npm run audit:file-manifest/, '_manifest is rebuilt');
  assert.match(b, /python3? scripts\/rebuild_manifest\.py/, 'manifest is rebuilt');
});

run('regeneration runs in the order the build step uses', () => {
  const block = /git rebase --abort[\s\S]*?git add "\$\{derived_artifacts\[@\]\}"/.exec(WF)[0];
  const snapshot = block.indexOf('build-home-snapshot.mjs');
  const places = block.indexOf('build_place_pages.py');
  const paper = block.indexOf('paper:build');
  const inventory = block.indexOf('compute-inventory.mjs');
  const under = block.indexOf('audit:file-manifest');
  const manifest = block.indexOf('rebuild_manifest.py');
  // rebuild_manifest.py records byte sizes of the tree the others have just
  // written, so running it earlier would bake in stale counts.
  assert.ok(snapshot < places && places < paper && paper < inventory && inventory < under && under < manifest,
    'order must be home-snapshot -> places -> paper -> inventory -> _manifest -> manifest, got ' +
    JSON.stringify({ snapshot, places, paper, inventory, under, manifest }));
});

run('derived-only recovery creates a commit instead of amending origin/main', () => {
  const guard = /if \[ "\$\(git rev-parse HEAD\)" = "\$\(git rev-parse origin\/main\)" \]; then[\s\S]{0,500}?else[\s\S]{0,100}?git commit --amend --no-edit/.exec(WF);
  assert.ok(guard, 'HEAD at origin/main must create a new commit; only a surviving bot commit may be amended');
  assert.match(guard[0], /git commit -m "chore: build HNA cache \+ scenarios data/,
    'derived-only recovery must create the normal dated HNA data commit');
});

run('recovery consistently references the derived set and uses no tab indentation', () => {
  const stepBodies = WF.split('\n').filter((l) => l.includes('derived_artifacts'));
  assert.ok(stepBodies.length >= 4, 'the array is referenced throughout the recovery');
  assert.ok(!/\t/.test(WF), 'no tabs — YAML indentation must stay spaces');
});

if (failures) { console.error('hna-build-rebase-recovery: FAIL'); process.exitCode = 1; }
else console.log('hna-build-rebase-recovery: PASS');
