#!/usr/bin/env node
/**
 * A Census call that cannot succeed must not be attempted.
 *
 * ── What was wrong ──
 *
 * The published site ships no Census API key — js/config.js says so on
 * purpose: "API keys are intentionally empty here; data is served from cached
 * JSON files generated by GitHub Actions."
 *
 * A keyless request to api.census.gov is not a request that might fail. Census
 * answers it with a 302 to missing_key.html which carries no
 * Access-Control-Allow-Origin header, so the browser rejects it as a CORS
 * block. fetch() surfaces that as a bare TypeError, indistinguishable from a
 * flaky network — so fetchWithTimeout retried it three times with 1s and 2s
 * backoff, and the vintage fallback walked 2024 -> 2023 -> 2022 -> 2021 doing
 * the same each time.
 *
 * Measured on https://cohoanalytics.com/hna-what-housing-exists.html
 * (place 0828745) on 2026-09-19, warm cache: 30 requests to 4 distinct URLs —
 * 26 of them retries — spanning 4.3s to 17.35s, and 207 console errors. The
 * "20-yr production need" card sat visibly reading "— Loading" from 738ms
 * until 17.6s, which is what a beta tester reported as a stuck card.
 *
 * Nothing was gained by the wait. _fetchCensusUrl already returned null on
 * every published page load, so every figure a visitor sees was already coming
 * from the cached JSON fallback.
 *
 * ── How this guard works ──
 *
 * It extracts the SHIPPED _fetchCensusUrl and _censusKeyConfigured out of
 * js/hna/hna-controller.js and RUNS them against a counting fetch stub, so it
 * measures behaviour rather than matching words in the source. A guard that
 * grepped for "CENSUS_API_KEY" would pass against the comment that mentions
 * it.
 *
 * Both directions are asserted: keyless must issue zero requests, and a
 * configured key must still reach the network. Without the second assertion
 * this guard would also pass against code that never calls Census at all.
 */
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import test from 'node:test';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const SRC = fs.readFileSync(path.join(ROOT, 'js/hna/hna-controller.js'), 'utf8');

/** Pull a named function's source out of the controller by brace matching. */
function extract(name) {
  let i = SRC.indexOf('function ' + name + '(');
  assert.ok(i >= 0, `${name}() is gone from hna-controller.js — this guard is checking nothing`);
  // Keep a leading `async`: slicing it off turns the body's top-level awaits
  // into a SyntaxError, which reads as a broken guard rather than a broken fix.
  if (SRC.slice(Math.max(0, i - 6), i) === 'async ') i -= 6;
  let depth = 0;
  for (let k = SRC.indexOf('{', i); k < SRC.length; k += 1) {
    if (SRC[k] === '{') depth += 1;
    else if (SRC[k] === '}') { depth -= 1; if (!depth) return SRC.slice(i, k + 1); }
  }
  throw new Error('unbalanced braces reading ' + name);
}

const URL_UNDER_TEST =
  'https://api.census.gov/data/2024/acs/acs5?get=NAME,B01001_001E&for=place:28745&in=state:08';

/**
 * Build a runnable _fetchCensusUrl over a counting fetch stub.
 * Every collaborator is a stub, so the only real code here is the shipped
 * function and its key check.
 */
function harness(censusKey) {
  const calls = [];
  const win = {
    APP_CONFIG: censusKey === undefined ? {} : { CENSUS_API_KEY: censusKey },
    // censusKey() is the shipped accessor, reproduced here exactly as
    // js/hna/hna-utils.js defines it, so the harness cannot disagree with it.
    HNAUtils: {
      redactKey: (u) => u,
      DEBUG_HNA: false,
      censusKey() {
        return (win.APP_CONFIG && win.APP_CONFIG.CENSUS_API_KEY) ? win.APP_CONFIG.CENSUS_API_KEY : '';
      },
    },
  };
  const fetchWithTimeout = async (url) => {
    calls.push(url);
    // Stand in for the live API answering normally.
    return { ok: true, status: 200, async text() { return '[]'; } };
  };
  const make = new Function(
    'window', 'fetchWithTimeout', 'console',
    `${extract('_censusGetVarsFromUrl')}
     function _assertCensusGetVariableLimit() {}
     ${extract('_censusKeyConfigured')}
     ${extract('_fetchCensusUrl')}
     return _fetchCensusUrl;`
  );
  return { fetchCensusUrl: make(win, fetchWithTimeout, console), calls };
}

test('with no key configured, no request is made and null is returned', async () => {
  for (const key of [undefined, '', '   ']) {
    const { fetchCensusUrl, calls } = harness(key);
    const resp = await fetchCensusUrl(URL_UNDER_TEST, 'ACS5 B01001 place:0828745 y=2024');
    assert.equal(calls.length, 0,
      `a keyless Census call reached the network (key=${JSON.stringify(key)}); ` +
      'it can only 302 to missing_key.html and fail CORS, and each attempt costs ' +
      'the visitor 3 retries with 1s/2s backoff across 4 vintages');
    assert.equal(resp, null,
      'callers treat null as "use the cached fallback"; anything else changes their path');
  }
});

test('with a key configured, the request is still made', async () => {
  const { fetchCensusUrl, calls } = harness('deadbeefdeadbeefdeadbeefdeadbeef');
  const resp = await fetchCensusUrl(URL_UNDER_TEST, 'ACS5 B01001 place:0828745 y=2024');
  assert.equal(calls.length, 1,
    'a developer who supplies a key through the Data Quality Dashboard must ' +
    'still reach the live API — otherwise the skip is not a skip, it is a removal');
  assert.equal(calls[0], URL_UNDER_TEST);
  assert.ok(resp && resp.ok, 'the live Response must be handed back untouched');
});
