// test/place-pages.test.js
//
// Phase 3 / C5 — validates the per-place HTML pages generated by
// scripts/hna/build_place_pages.py.
//
// What it asserts
//   - Generator script + template exist + are well-formed
//   - All 464+ pages generated have key data baked in
//   - Cross-county jurisdictions (Aurora, Erie, Longmont) have
//     disclosure data in their embedded JSON
//   - Index page lists all generated places
//   - Each page links to Deal Calculator + PMA + HNA
//   - canonical link present for SEO
//
// Run: node test/place-pages.test.js

'use strict';

const fs   = require('fs');
const path = require('path');

let passed = 0;
let failed = 0;

function assert(cond, msg) {
  if (cond) { console.log('  ✅ PASS: ' + msg); passed++; }
  else { console.error('  ❌ FAIL: ' + msg); failed++; }
}

function readRel(rel) {
  return fs.readFileSync(path.join(__dirname, '..', rel), 'utf8');
}

console.log('\n[test] Generator script + template');
const generator = readRel('scripts/hna/build_place_pages.py');
assert(/def generate_page/.test(generator),
  'generator has generate_page() function');
assert(/def build_index/.test(generator),
  'generator has build_index() function');
assert(/cross_county/.test(generator),
  'generator handles cross-county disclosure');
assert(/canonical/.test(generator),
  'generator emits canonical link for SEO');

console.log('\n[test] places/ directory structure');
const placesDir = path.join(__dirname, '..', 'places');
const files = fs.readdirSync(placesDir);
const pageFiles = files.filter(f => /^08\d{5}\.html$/.test(f));
assert(pageFiles.length >= 400,
  '≥400 place pages generated (found ' + pageFiles.length + ')');
assert(files.includes('index.html'),
  'index.html exists');
assert(files.includes('_template.html'),
  '_template.html exists');

console.log('\n[test] Index page lists all places');
const indexHtml = readRel('places/index.html');
const liCount = (indexHtml.match(/<li>/g) || []).length;
assert(liCount >= 400,
  'index has ≥400 list items (found ' + liCount + ')');
assert(/<h1>Colorado Places/.test(indexHtml),
  'index has Colorado Places heading');

console.log('\n[test] Erie (cross-county) page surfaces disclosure');
// Erie's geoid is 0824950
if (pageFiles.includes('0824950.html')) {
  const erie = readRel('places/0824950.html');
  assert(/Erie/.test(erie),
    'Erie page title contains "Erie"');
  assert(/cross_county/.test(erie),
    'Erie page has cross_county data embedded');
  // Should mention both counties
  assert(/Boulder/.test(erie),
    'Erie page mentions Boulder County');
  assert(/Weld/.test(erie),
    'Erie page mentions Weld County');
} else {
  console.warn('  ⚠ Erie page (0824950.html) not generated; skipping');
}

console.log('\n[test] Aurora (3-county cross-county) page');
if (pageFiles.includes('0804000.html')) {
  const aurora = readRel('places/0804000.html');
  assert(/Aurora/.test(aurora),
    'Aurora page title contains "Aurora"');
  assert(/Arapahoe|Adams|Douglas/.test(aurora),
    'Aurora page mentions one of Arapahoe/Adams/Douglas');
}

console.log('\n[test] Each page has the expected dashboard cards');
// Spot-check a small page
const spotPage = readRel('places/' + pageFiles[0]);
['psRenterCb30','psRenterCb50','psOwnerCb30','psRenterTotal','psOwnerTotal',
 'psTierLte30','psTier3150','psTier5180','psTier81100','psTier100p',
 'psSource','psTracts','psCoverage'].forEach(id => {
  assert(spotPage.includes('id="' + id + '"'),
    'page has #' + id);
});
assert(/canonical/.test(spotPage),
  'page has canonical link');
assert(/og:title|og:description/.test(spotPage),
  'page has Open Graph metadata');

console.log('\n[test] Pages link back to workflow tools');
['deal-calculator', 'market-analysis', 'housing-needs-assessment'].forEach(t => {
  assert(spotPage.includes(t + '.html'),
    'page links to ' + t + '.html');
});

console.log('\n[test] Embedded place-data JSON parses');
const dataMatch = spotPage.match(/<script id="place-data" type="application\/json">\s*([\s\S]*?)\s*<\/script>/);
assert(dataMatch != null,
  'page has place-data JSON script tag');
if (dataMatch) {
  let parsed = null;
  try { parsed = JSON.parse(dataMatch[1]); } catch (_) {}
  assert(parsed != null && typeof parsed === 'object',
    'embedded JSON parses cleanly');
  if (parsed) {
    assert(typeof parsed.name === 'string',
      'embedded JSON has name');
    assert(parsed.summary && typeof parsed.summary === 'object',
      'embedded JSON has summary block');
  }
}

console.log('\n=========================================');
console.log('Results: ' + passed + ' passed, ' + failed + ' failed');
process.exit(failed === 0 ? 0 : 1);
