'use strict';
/**
 * test/place-lehd-apportionment.test.js
 *
 * Regression for 2026-05-16 feature work: TIGER-derived place-level
 * LEHD WAC, generated by scripts/hna/build_place_lehd.py and surfaced
 * via window.PlaceLehd. Before this feature, every place/cdp
 * selection on HNA silently inherited the parent county's wage /
 * industry numbers (only a "County-level data" amber disclosure
 * surfaced the misattribution).
 *
 * What this test asserts:
 *   1. The generated data file has correct shape + a Paonia entry.
 *   2. Paonia's apportioned C000 is plausibly small (≪ Delta's full
 *      county C000); the bug it replaces was scaling jobs at ~0.04%
 *      of Delta's count because of area-weighted tract pop.
 *   3. js/place-lehd-lookup.js exposes init/lookup/confidence on
 *      window.PlaceLehd.
 *   4. The HNA controller looks up PlaceLehd for place/cdp selections
 *      and swaps the lehd object before downstream rendering.
 *   5. CSS has a green --place variant of the county-scope note.
 *
 * Run: node test/place-lehd-apportionment.test.js
 */

const fs   = require('fs');
const path = require('path');

let passed = 0, failed = 0;
function assert(cond, msg) {
  if (cond) { console.log('  ✅ PASS:', msg); passed++; }
  else       { console.error('  ❌ FAIL:', msg); failed++; }
}

const root = path.join(__dirname, '..');

console.log('\n[test] data/hna/place-lehd.json shape + Paonia spot-check');
const placeLehd = JSON.parse(fs.readFileSync(path.join(root, 'data/hna/place-lehd.json'), 'utf8'));
assert(placeLehd.meta && placeLehd.places,
  'top-level has meta + places');
assert(placeLehd.meta.method && /apportionment/i.test(placeLehd.meta.method),
  'meta.method documents the apportionment approach');
const paonia = placeLehd.places['0857300'];
assert(paonia != null, 'Paonia (0857300) entry exists');
if (paonia) {
  assert(paonia.counties_spanned && paonia.counties_spanned.includes('08029'),
    'Paonia counties_spanned includes Delta County (08029)');
  // Delta has ~14,000 LEHD jobs; Paonia is ~5% of Delta. Apportioned
  // C000 should land in the low-hundreds, not single digits (the
  // pre-fix bug) and not thousands (county-level leakage).
  assert(paonia.lehd && paonia.lehd.C000 > 50 && paonia.lehd.C000 < 2000,
    'Paonia apportioned C000 is in the realistic 50–2000 range (got ' + (paonia.lehd && paonia.lehd.C000) + ')');
  assert(paonia.lehd && Array.isArray(paonia.lehd.industries) && paonia.lehd.industries.length > 0,
    'Paonia has a non-empty industries[] array');
  assert(paonia.coverage_confidence === 'high' ||
         paonia.coverage_confidence === 'medium' ||
         paonia.coverage_confidence === 'low',
    'Paonia has a coverage_confidence label');
}

console.log('\n[test] js/place-lehd-lookup.js public API');
const lookupSrc = fs.readFileSync(path.join(root, 'js/place-lehd-lookup.js'), 'utf8');
assert(/window\.PlaceLehd\s*=\s*\{[\s\S]*init[\s\S]*lookup[\s\S]*confidence/.test(lookupSrc),
  'exposes init / lookup / confidence on window.PlaceLehd');
assert(/data\/hna\/place-lehd\.json|hna\/place-lehd\.json/.test(lookupSrc),
  'fetches data/hna/place-lehd.json');

console.log('\n[test] controller wires PlaceLehd into the labor-market pipeline');
const ctlSrc = fs.readFileSync(path.join(root, 'js/hna/hna-controller.js'), 'utf8');
assert(/window\.PlaceLehd\.lookup\(geoid\)/.test(ctlSrc),
  'controller looks up the place blob from window.PlaceLehd');
assert(/placeLehdUsed\s*=\s*true/.test(ctlSrc),
  'sets a placeLehdUsed flag when the swap happens');
assert(/mode:\s*['"]place-apportioned['"]/.test(ctlSrc),
  'controller passes mode: "place-apportioned" to the disclosure renderer');

console.log('\n[test] HTML loads the lookup script defer-style');
const html = fs.readFileSync(path.join(root, 'housing-needs-assessment.html'), 'utf8');
assert(/script\s+defer\s+src="js\/place-lehd-lookup\.js"/.test(html),
  'place-lehd-lookup.js script tag is in housing-needs-assessment.html');

console.log('\n[test] CSS green --place variant');
const css = fs.readFileSync(path.join(root, 'css/site-theme.css'), 'utf8');
const placeVariant = css.match(/\.hna-county-scope-note--place\s*\{([\s\S]*?)\}/);
assert(placeVariant != null, '.hna-county-scope-note--place block exists');
if (placeVariant) {
  assert(/var\(--good/.test(placeVariant[1]),
    'uses the good-color token (green left-border)');
}

console.log('\n=========================================');
console.log('Results: ' + passed + ' passed, ' + failed + ' failed');
process.exit(failed === 0 ? 0 : 1);
