"""tests/test_hna_ranking_integrity.py
Regression guards for `data/hna/ranking-index.json` produced by
`scripts/hna/build_ranking_index.py`.

Prior bugs these probes exist to prevent reintroducing:

1. Naming inconsistency between ranking-index and geo-config —
   ranking-index used to ship "Boulder city" while geo-config used
   "Boulder (city)", causing name-based joins (dropdowns, comparison
   selectors) to silently fail.

2. County-level LEHD inflow leaked into place/CDP rows. Fruita (city)
   used to show Mesa County's full ~12,400 in-commuter count.

3. Owner % stored as renter % — Fruita used to ship pct_renters=79.9
   (the owner percentage). Symptom of stale data generated by an older
   buggy script and never re-built.

4. Boulder (city) entry stripped of all enrichment metrics due to
   keying mismatch downstream of #1.

These tests assert structural invariants on the *current* on-disk
ranking-index. Run after every regeneration. They are cheap (one JSON
load).
"""

import glob
import importlib.util
import json
import math
import os

import pytest

REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
RANKING_PATH = os.path.join(REPO_ROOT, 'data', 'hna', 'ranking-index.json')
SUMMARY_DIR  = os.path.join(REPO_ROOT, 'data', 'hna', 'summary')


@pytest.fixture(scope='module')
def ranking():
    """Load ranking-index.json once per test module."""
    with open(RANKING_PATH, 'r', encoding='utf-8') as f:
        return json.load(f)


@pytest.fixture(scope='module')
def entries(ranking):
    """All ranking entries as a list."""
    return ranking['rankings']


@pytest.fixture(scope='module')
def counties_by_fips(entries):
    """County entries keyed by 5-digit FIPS for cross-joins."""
    return {e['geoid']: e for e in entries if e.get('type') == 'county'}


@pytest.fixture(scope='module')
def ranking_builder():
    """Load build_ranking_index.py as a module for helper-level guards."""
    path = os.path.join(REPO_ROOT, 'scripts', 'hna', 'build_ranking_index.py')
    spec = importlib.util.spec_from_file_location('build_ranking_index', path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


# ---------------------------------------------------------------------------
# Naming invariants (Bug #1, #4)
# ---------------------------------------------------------------------------

class TestNamingFormat:
    """Place/CDP names must use the parenthetical form so name-based joins
    against geo-config.json and geography-registry.json keep working."""

    def test_every_place_name_uses_parens(self, entries):
        bad = [
            f"{e['geoid']}: {e['name']!r}"
            for e in entries
            if e.get('type') == 'place' and '(' not in e.get('name', '')
        ]
        assert not bad, (
            'Place entries missing parenthetical suffix in name '
            '(e.g. "Boulder city" instead of "Boulder (city)"). '
            'Breaks name-based joins to geo-config.json.\n'
            + '\n'.join(bad[:10])
        )

    def test_every_cdp_name_uses_parens(self, entries):
        bad = [
            f"{e['geoid']}: {e['name']!r}"
            for e in entries
            if e.get('type') == 'cdp' and '(' not in e.get('name', '')
        ]
        assert not bad, (
            'CDP entries missing parenthetical suffix in name. '
            'Breaks name-based joins.\n'
            + '\n'.join(bad[:10])
        )

    def test_county_names_end_with_county_suffix(self, entries):
        bad = [
            f"{e['geoid']}: {e['name']!r}"
            for e in entries
            if e.get('type') == 'county' and not e.get('name', '').endswith('County')
        ]
        # Broomfield is "Broomfield County" too, no exceptions expected
        assert not bad, (
            'County entries should be labeled "<Name> County".\n'
            + '\n'.join(bad[:5])
        )


# ---------------------------------------------------------------------------
# LEHD inflow scaling (Bug #2)
# ---------------------------------------------------------------------------

class TestLehdInflowScaling:
    """A place/CDP's in_commuters must never exceed its enclosing county's
    in_commuters. If it does, the LEHD county-total leaked into the place
    row instead of being scaled by population share."""

    def _containing_county_fips(self, geoid):
        """Read containingCounty from the place/CDP's summary file."""
        path = os.path.join(SUMMARY_DIR, f'{geoid}.json')
        if not os.path.exists(path):
            return None
        with open(path, 'r', encoding='utf-8') as f:
            return json.load(f).get('geo', {}).get('containingCounty')

    def test_place_in_commuters_does_not_exceed_county(self, entries, counties_by_fips):
        """Guard against the old county-total leak.

        Places spanning multiple counties can legitimately exceed any
        single containing county's inflow once place-LEHD apportionment
        is in play (per the spatial-membership method documented in
        data/hna/place-lehd.json:meta.method). Skip rows that resolved
        via the place-LEHD path — the assertion only meaningfully
        guards the legacy ``county_proportional`` fallback.
        """
        violations = []
        for e in entries:
            if e.get('type') not in ('place', 'cdp'):
                continue
            # Place-LEHD apportions across the tracts a place spans —
            # for multi-county places the sum can exceed any single
            # county. The leak this test was built to catch only
            # affected the legacy county-scaled fallback.
            if e['metrics'].get('_lehd_source') == 'place':
                continue
            place_inflow = e['metrics'].get('in_commuters', 0)
            if place_inflow == 0:
                continue
            county_fips = self._containing_county_fips(e['geoid'])
            if not county_fips or county_fips not in counties_by_fips:
                continue
            county_inflow = counties_by_fips[county_fips]['metrics'].get('in_commuters', 0)
            if county_inflow == 0:
                continue
            if place_inflow > county_inflow:
                violations.append(
                    f"{e['name']} ({e['geoid']}): place={place_inflow:,} > "
                    f"county {county_fips}={county_inflow:,}"
                )
        assert not violations, (
            'LEHD county-total leaked into place/CDP rows '
            '(in_commuters should be scaled by population share).\n'
            + '\n'.join(violations[:10])
        )

    def test_fruita_in_commuters_within_plausible_range(self, entries):
        """Fruita (city) had ~12,400 in_commuters before the fix (the full
        Mesa County total). Scaled by population share, it should be a
        small fraction of that — under 3,000."""
        fruita = next(
            (e for e in entries if e.get('name') == 'Fruita (city)'),
            None,
        )
        assert fruita is not None, 'Fruita (city) missing from ranking-index'
        inflow = fruita['metrics'].get('in_commuters', 0)
        assert 0 < inflow < 3000, (
            f'Fruita (city) in_commuters={inflow:,} is implausible. '
            'Expected a small fraction of Mesa County\'s ~12k. '
            'Likely regression of LEHD county-total leak.'
        )


# ---------------------------------------------------------------------------
# pct_renters sanity (Bug #3)
# ---------------------------------------------------------------------------

class TestPctRentersSanity:
    """pct_renters must be a percentage (0–100) and must come from the
    correct ACS DP04_0047PE field, not the owner-occupied DP04_0046PE
    field. Regression check: confirm at least one well-known suburban
    place reports a renter share well below 50%."""

    def test_pct_renters_is_within_zero_to_one_hundred(self, entries):
        bad = [
            f"{e['name']}: pct_renters={e['metrics'].get('pct_renters')}"
            for e in entries
            if not (0 <= e['metrics'].get('pct_renters', 0) <= 100)
        ]
        assert not bad, (
            'pct_renters out of [0, 100] range:\n' + '\n'.join(bad[:10])
        )

    def test_fruita_pct_renters_below_50(self, entries):
        """Fruita (city) is a small suburban Mesa-County town. Real ACS
        renter share is ~20%. The pre-fix value was 79.9% (the owner-
        occupied percentage, swapped). Anything ≥ 50% is suspicious."""
        fruita = next(
            (e for e in entries if e.get('name') == 'Fruita (city)'),
            None,
        )
        assert fruita is not None, 'Fruita (city) missing from ranking-index'
        pct = fruita['metrics'].get('pct_renters', 0)
        assert pct < 50, (
            f'Fruita (city) pct_renters={pct} is implausibly high — '
            'likely owner-occupied percentage written into the renter '
            'field. Re-check that compute_metrics reads DP04_0047PE '
            '(renter %) and not DP04_0046PE (owner %).'
        )


# ---------------------------------------------------------------------------
# Enrichment completeness (Bug #4)
# ---------------------------------------------------------------------------

class TestEnrichmentCompleteness:
    """Every well-known city should have a non-empty metrics dict.
    Boulder (city) was once stripped of all enrichment due to a name-key
    mismatch — make sure that doesn't recur."""

    REQUIRED_METRIC_KEYS = (
        'housing_gap_units',
        'pct_cost_burdened',
        'in_commuters',
        'population',
        'population_projection_20yr',
        'pct_renters',
    )

    @pytest.mark.parametrize('place_name', ['Boulder (city)', 'Denver (city)', 'Aurora (city)'])
    def test_well_known_city_has_full_enrichment(self, entries, place_name):
        entry = next((e for e in entries if e.get('name') == place_name), None)
        assert entry is not None, f'{place_name} missing from ranking-index'
        m = entry['metrics']
        missing = [k for k in self.REQUIRED_METRIC_KEYS if k not in m]
        assert not missing, (
            f'{place_name} missing metric keys: {missing}'
        )
        assert m.get('population', 0) > 0, (
            f'{place_name} has population=0 — likely orphaned entry'
        )


# ---------------------------------------------------------------------------
# Tenure orientation consistency (renter vs owner)
# ---------------------------------------------------------------------------

class TestTenureOrientation:
    """Guard against renter/owner percentage reversals across ETL outputs."""

    def test_state_summary_tenure_aligns_with_county_weighted_average(self):
        state_path = os.path.join(SUMMARY_DIR, '08.json')
        with open(state_path, 'r', encoding='utf-8') as f:
            state = json.load(f)

        state_profile = state.get('acsProfile', {})
        state_renter = float(state_profile.get('DP04_0047PE', 0))

        weighted_num = 0.0
        weighted_den = 0.0

        for fp in glob.glob(os.path.join(SUMMARY_DIR, '08???.json')):
            with open(fp, 'r', encoding='utf-8') as f:
                rec = json.load(f)
            if rec.get('geo', {}).get('type') != 'county':
                continue
            prof = rec.get('acsProfile', {})
            pop = float(prof.get('DP05_0001E', 0) or 0)
            renter = float(prof.get('DP04_0047PE', 0) or 0)
            if pop <= 0:
                continue
            weighted_num += pop * renter
            weighted_den += pop

        assert weighted_den > 0, 'No county population weights available for tenure validation'
        county_weighted_renter = weighted_num / weighted_den

        assert abs(state_renter - county_weighted_renter) < 5.0, (
            f"State renter share DP04_0047PE={state_renter:.1f}% is inconsistent with "
            f"county-weighted renter share ({county_weighted_renter:.1f}%). "
            "Likely renter/owner reversal in state summary tenure fields."
        )


# ---------------------------------------------------------------------------
# Ranking score normalization
# ---------------------------------------------------------------------------

class TestRankingScoreNormalization:
    """Overall need scoring should compare like geographies and keep the
    commuter term blended between absolute and size-normalized pressure."""

    def test_percentile_ranks_can_be_scoped_by_geo_type(self, ranking_builder):
        sample = [
            {'geoid': 'c-low', 'type': 'county', 'metrics': {'housing_gap_units': 10}},
            {'geoid': 'c-high', 'type': 'county', 'metrics': {'housing_gap_units': 20}},
            {'geoid': 'p-low', 'type': 'place', 'metrics': {'housing_gap_units': 1}},
            {'geoid': 'p-high', 'type': 'place', 'metrics': {'housing_gap_units': 2}},
        ]
        mixed = ranking_builder.compute_percentile_ranks(sample, 'housing_gap_units')
        scoped = ranking_builder.compute_percentile_ranks(
            sample, 'housing_gap_units', within_geo_type=True
        )

        assert mixed['p-high'] < mixed['c-low'], (
            'Mixed-pool ranking should still rank the small place below the county; '
            'this confirms the fixture differentiates the two modes.'
        )
        assert scoped['p-high'] == 100.0
        assert scoped['c-high'] == 100.0
        assert scoped['p-low'] == 0.0
        assert scoped['c-low'] == 0.0

    def test_commuter_pressure_score_is_materialized(self, entries):
        missing = [
            f"{e['geoid']} {e['name']}"
            for e in entries
            if 'commuter_pressure_score' not in e.get('metrics', {})
        ]
        assert not missing, (
            'ranking-index entries must include commuter_pressure_score so '
            'reviewers can audit the blended commuter term.\n' + '\n'.join(missing[:10])
        )

    def test_commuter_pressure_score_stays_in_range(self, entries):
        bad = [
            f"{e['geoid']} {e['name']}: {e['metrics'].get('commuter_pressure_score')}"
            for e in entries
            if not (0 <= e['metrics'].get('commuter_pressure_score', -1) <= 100)
        ]
        assert not bad, (
            'commuter_pressure_score outside [0, 100]:\n' + '\n'.join(bad[:10])
        )

    def test_percentile_ranks_ignore_missing_rate_values(self, ranking_builder):
        sample = [
            {'geoid': 'p-missing', 'type': 'place', 'metrics': {'housing_gap_rate_lte30': None}},
            {'geoid': 'p-low', 'type': 'place', 'metrics': {'housing_gap_rate_lte30': 10}},
            {'geoid': 'p-high', 'type': 'place', 'metrics': {'housing_gap_rate_lte30': 90}},
        ]
        scoped = ranking_builder.compute_percentile_ranks(
            sample, 'housing_gap_rate_lte30', within_geo_type=True
        )

        assert 'p-missing' not in scoped
        assert scoped['p-low'] == 0.0
        assert scoped['p-high'] == 100.0

    def test_b1_factor_scores_are_materialized_and_bounded(self, entries):
        factor_keys = (
            'gap_pressure_score',
            'cost_burden_pressure_score',
            'affordability_intensity_score',
            'future_pressure_score',
            'commuter_pressure_score',
        )
        bad = []
        for entry in entries:
            metrics = entry.get('metrics', {})
            for key in factor_keys:
                val = metrics.get(key)
                if not isinstance(val, (int, float)) or not (0 <= val <= 100):
                    bad.append(f"{entry['geoid']} {entry['name']} {key}={val}")

        assert not bad, 'B1 factor score missing or outside [0, 100]:\n' + '\n'.join(bad[:10])

    def test_gap_rate_uses_low_income_household_denominator(self, entries):
        silt = next((e for e in entries if e.get('geoid') == '0870195'), None)
        assert silt is not None, 'Silt missing from ranking-index'
        metrics = silt['metrics']

        assert metrics['low_income_households_lte30'] == 171
        assert metrics['housing_gap_units'] == 157
        assert metrics['housing_gap_rate_lte30'] == pytest.approx(91.8, abs=0.1)

    def test_confidence_multiplier_reflects_imputed_inputs(self, entries):
        bad = []
        seen_penalized = False
        for entry in entries:
            metrics = entry.get('metrics', {})
            mult = metrics.get('score_confidence_multiplier')
            if not isinstance(mult, (int, float)) or not (0.85 <= mult <= 1.0):
                bad.append(f"{entry['geoid']} {entry['name']} multiplier={mult}")
            if entry.get('dataQuality', {}).get('imputed_score_factors'):
                seen_penalized = True
                assert entry.get('hasIncompleteData') is True
                assert mult < 1.0

        assert not bad, 'Invalid score_confidence_multiplier:\n' + '\n'.join(bad[:10])
        assert seen_penalized, 'Expected at least one entry with imputed B1 score factors'

    def test_qap_axes_are_materialized_and_bounded(self, entries):
        axis_keys = ('community_need_score', 'opportunity_score', 'overall_need_score')
        bad = []
        for entry in entries:
            metrics = entry.get('metrics', {})
            for key in axis_keys:
                val = metrics.get(key)
                if not isinstance(val, (int, float)) or not (0 <= val <= 100):
                    bad.append(f"{entry['geoid']} {entry['name']} {key}={val}")

        assert not bad, 'QAP axis score missing or outside [0, 100]:\n' + '\n'.join(bad[:10])

    def test_opportunity_layer_coverage_and_context(self, entries):
        missing = []
        for entry in entries:
            metrics = entry.get('metrics', {})
            if not isinstance(metrics.get('opportunity_score'), (int, float)):
                missing.append(f"{entry['geoid']} {entry['name']}: opportunity_score missing")
            if not isinstance(metrics.get('amenity_access_score'), (int, float)):
                missing.append(f"{entry['geoid']} {entry['name']}: amenity_access_score missing")
            if not isinstance(metrics.get('qct_dda_score'), (int, float)):
                missing.append(f"{entry['geoid']} {entry['name']}: qct_dda_score missing")
            if entry.get('type') == 'county':
                assert metrics.get('opportunity_geography_level') == 'county_context'

        assert not missing, 'Opportunity layer coverage gaps:\n' + '\n'.join(missing[:10])

    def test_no_nan_metrics_in_ranking_index(self, entries):
        bad = []
        for entry in entries:
            for key, value in entry.get('metrics', {}).items():
                if isinstance(value, float) and math.isnan(value):
                    bad.append(f"{entry['geoid']} {entry['name']} {key}=NaN")

        assert not bad, 'NaN metric values found:\n' + '\n'.join(bad[:10])

    def test_commuter_augment_only_never_reduces_community_need(self, entries):
        bad = []
        for entry in entries:
            metrics = entry.get('metrics', {})
            core = metrics.get('community_need_core_score')
            augmented = metrics.get('community_need_augmented_raw')
            if isinstance(core, (int, float)) and isinstance(augmented, (int, float)):
                if augmented + 0.1 < core:
                    bad.append(f"{entry['geoid']} {entry['name']}: core={core} augmented={augmented}")

        assert not bad, 'Commuter augment reduced community need:\n' + '\n'.join(bad[:10])

    def test_commuter_alpha_math_for_silt(self, entries, ranking_builder):
        silt = next((e for e in entries if e.get('geoid') == '0870195'), None)
        assert silt is not None, 'Silt missing from ranking-index'
        metrics = silt['metrics']
        expected = min(
            100.0,
            metrics['community_need_core_score'] * (
                1 + ranking_builder.COMMUTER_AUGMENT_ALPHA * metrics['commuter_pressure_score'] / 100
            ),
        )
        assert metrics['community_need_augmented_raw'] == pytest.approx(expected, abs=0.2)

    def test_overcrowding_absence_does_not_penalize_all_entries(self, entries):
        absent = next(
            (
                e for e in entries
                if e['metrics'].get('overcrowding_rate') is None
                and (e['metrics'].get('community_need_core_score') or 0) > 0
            ),
            None,
        )
        assert absent is not None, 'expected an entry with no overcrowding data'
        metrics = absent['metrics']
        assert metrics.get('overcrowding_rate') is None
        assert metrics.get('overcrowding_score') is None
        assert 'overcrowding_rate' not in absent.get('dataQuality', {}).get('imputed_score_factors', [])
        assert metrics.get('community_need_core_score', 0) > 0
