"""tests/test_hna_ranking_integrity.py
Regression guards for `data/hna/ranking-index.json` produced by
`scripts/hna/build_ranking_index.py`.

Prior bugs these probes exist to prevent reintroducing:

1. Naming inconsistency between ranking-index and geo-config —
   ranking-index used to ship "Boulder city" while geo-config used
   "Boulder (city)", causing name-based joins (dropdowns, comparison
   selectors) to silently fail.

2. County-level LEHD inflow leaked into place/CDP rows. Fruita (city)
   used to show Mesa County's full ~12,400 in-commuter count.

3. Owner % stored as renter % — Fruita used to ship pct_renters=79.9
   (the owner percentage). Symptom of stale data generated by an older
   buggy script and never re-built.

4. Boulder (city) entry stripped of all enrichment metrics due to
   keying mismatch downstream of #1.

These tests assert structural invariants on the *current* on-disk
ranking-index. Run after every regeneration. They are cheap (one JSON
load).
"""

import glob
import json
import os

import pytest

REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
RANKING_PATH = os.path.join(REPO_ROOT, 'data', 'hna', 'ranking-index.json')
SUMMARY_DIR  = os.path.join(REPO_ROOT, 'data', 'hna', 'summary')


@pytest.fixture(scope='module')
def ranking():
    """Load ranking-index.json once per test module."""
    with open(RANKING_PATH, 'r', encoding='utf-8') as f:
        return json.load(f)


@pytest.fixture(scope='module')
def entries(ranking):
    """All ranking entries as a list."""
    return ranking['rankings']


@pytest.fixture(scope='module')
def counties_by_fips(entries):
    """County entries keyed by 5-digit FIPS for cross-joins."""
    return {e['geoid']: e for e in entries if e.get('type') == 'county'}


# ---------------------------------------------------------------------------
# Naming invariants (Bug #1, #4)
# ---------------------------------------------------------------------------

class TestNamingFormat:
    """Place/CDP names must use the parenthetical form so name-based joins
    against geo-config.json and geography-registry.json keep working."""

    def test_every_place_name_uses_parens(self, entries):
        bad = [
            f"{e['geoid']}: {e['name']!r}"
            for e in entries
            if e.get('type') == 'place' and '(' not in e.get('name', '')
        ]
        assert not bad, (
            'Place entries missing parenthetical suffix in name '
            '(e.g. "Boulder city" instead of "Boulder (city)"). '
            'Breaks name-based joins to geo-config.json.\n'
            + '\n'.join(bad[:10])
        )

    def test_every_cdp_name_uses_parens(self, entries):
        bad = [
            f"{e['geoid']}: {e['name']!r}"
            for e in entries
            if e.get('type') == 'cdp' and '(' not in e.get('name', '')
        ]
        assert not bad, (
            'CDP entries missing parenthetical suffix in name. '
            'Breaks name-based joins.\n'
            + '\n'.join(bad[:10])
        )

    def test_county_names_end_with_county_suffix(self, entries):
        bad = [
            f"{e['geoid']}: {e['name']!r}"
            for e in entries
            if e.get('type') == 'county' and not e.get('name', '').endswith('County')
        ]
        # Broomfield is "Broomfield County" too, no exceptions expected
        assert not bad, (
            'County entries should be labeled "<Name> County".\n'
            + '\n'.join(bad[:5])
        )


# ---------------------------------------------------------------------------
# LEHD inflow scaling (Bug #2)
# ---------------------------------------------------------------------------

class TestLehdInflowScaling:
    """A place/CDP's in_commuters must never exceed its enclosing county's
    in_commuters. If it does, the LEHD county-total leaked into the place
    row instead of being scaled by population share."""

    def _containing_county_fips(self, geoid):
        """Read containingCounty from the place/CDP's summary file."""
        path = os.path.join(SUMMARY_DIR, f'{geoid}.json')
        if not os.path.exists(path):
            return None
        with open(path, 'r', encoding='utf-8') as f:
            return json.load(f).get('geo', {}).get('containingCounty')

    def test_place_in_commuters_does_not_exceed_county(self, entries, counties_by_fips):
        violations = []
        for e in entries:
            if e.get('type') not in ('place', 'cdp'):
                continue
            place_inflow = e['metrics'].get('in_commuters', 0)
            if place_inflow == 0:
                continue
            county_fips = self._containing_county_fips(e['geoid'])
            if not county_fips or county_fips not in counties_by_fips:
                continue
            county_inflow = counties_by_fips[county_fips]['metrics'].get('in_commuters', 0)
            if county_inflow == 0:
                continue
            if place_inflow > county_inflow:
                violations.append(
                    f"{e['name']} ({e['geoid']}): place={place_inflow:,} > "
                    f"county {county_fips}={county_inflow:,}"
                )
        assert not violations, (
            'LEHD county-total leaked into place/CDP rows '
            '(in_commuters should be scaled by population share).\n'
            + '\n'.join(violations[:10])
        )

    def test_fruita_in_commuters_within_plausible_range(self, entries):
        """Fruita (city) had ~12,400 in_commuters before the fix (the full
        Mesa County total). Scaled by population share, it should be a
        small fraction of that — under 3,000."""
        fruita = next(
            (e for e in entries if e.get('name') == 'Fruita (city)'),
            None,
        )
        assert fruita is not None, 'Fruita (city) missing from ranking-index'
        inflow = fruita['metrics'].get('in_commuters', 0)
        assert 0 < inflow < 3000, (
            f'Fruita (city) in_commuters={inflow:,} is implausible. '
            'Expected a small fraction of Mesa County\'s ~12k. '
            'Likely regression of LEHD county-total leak.'
        )


# ---------------------------------------------------------------------------
# pct_renters sanity (Bug #3)
# ---------------------------------------------------------------------------

class TestPctRentersSanity:
    """pct_renters must be a percentage (0–100) and must come from the
    correct ACS DP04_0047PE field, not the owner-occupied DP04_0046PE
    field. Regression check: confirm at least one well-known suburban
    place reports a renter share well below 50%."""

    def test_pct_renters_is_within_zero_to_one_hundred(self, entries):
        bad = [
            f"{e['name']}: pct_renters={e['metrics'].get('pct_renters')}"
            for e in entries
            if not (0 <= e['metrics'].get('pct_renters', 0) <= 100)
        ]
        assert not bad, (
            'pct_renters out of [0, 100] range:\n' + '\n'.join(bad[:10])
        )

    def test_fruita_pct_renters_below_50(self, entries):
        """Fruita (city) is a small suburban Mesa-County town. Real ACS
        renter share is ~20%. The pre-fix value was 79.9% (the owner-
        occupied percentage, swapped). Anything ≥ 50% is suspicious."""
        fruita = next(
            (e for e in entries if e.get('name') == 'Fruita (city)'),
            None,
        )
        assert fruita is not None, 'Fruita (city) missing from ranking-index'
        pct = fruita['metrics'].get('pct_renters', 0)
        assert pct < 50, (
            f'Fruita (city) pct_renters={pct} is implausibly high — '
            'likely owner-occupied percentage written into the renter '
            'field. Re-check that compute_metrics reads DP04_0047PE '
            '(renter %) and not DP04_0046PE (owner %).'
        )


# ---------------------------------------------------------------------------
# Enrichment completeness (Bug #4)
# ---------------------------------------------------------------------------

class TestEnrichmentCompleteness:
    """Every well-known city should have a non-empty metrics dict.
    Boulder (city) was once stripped of all enrichment due to a name-key
    mismatch — make sure that doesn't recur."""

    REQUIRED_METRIC_KEYS = (
        'housing_gap_units',
        'pct_cost_burdened',
        'in_commuters',
        'population',
        'population_projection_20yr',
        'pct_renters',
    )

    @pytest.mark.parametrize('place_name', ['Boulder (city)', 'Denver (city)', 'Aurora (city)'])
    def test_well_known_city_has_full_enrichment(self, entries, place_name):
        entry = next((e for e in entries if e.get('name') == place_name), None)
        assert entry is not None, f'{place_name} missing from ranking-index'
        m = entry['metrics']
        missing = [k for k in self.REQUIRED_METRIC_KEYS if k not in m]
        assert not missing, (
            f'{place_name} missing metric keys: {missing}'
        )
        assert m.get('population', 0) > 0, (
            f'{place_name} has population=0 — likely orphaned entry'
        )
