#!/usr/bin/env python3
"""
scripts/hna/build_hna_views.py

Generate the task-oriented Housing Needs Assessment views from the canonical
page, one per question a reader arrives with.

WHY GENERATED AND NOT AUTHORED
------------------------------
housing-needs-assessment.html stays the canonical page AND the full report: it
keeps all 53 sections, hna-export.js and print.css's A4 title-page margin, so
the PDF deliverable a planner cites is byte-for-byte the artifact it is today.
The views are cut FROM it, so a figure is never authored twice and the views
cannot disagree with the report. Same pattern as build_place_pages.py, which
generates 482 place pages from a shared template.

Sections are matched on <h2> text (prefix, case-insensitive) and removed by
balanced-tag scan of the enclosing <section> or <div>, so a view is the
canonical page minus what it does not answer. Everything else -- head,
scripts, nav, data loading -- is inherited untouched.

    python3 scripts/hna/build_hna_views.py           # write the views
    python3 scripts/hna/build_hna_views.py --check    # verify they are current

Exit codes: 0 ok · 1 drift (--check) · 2 mapping or source error
"""
import json, os, re, sys, html as htmllib

ROOT     = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SOURCE   = os.path.join(ROOT, 'housing-needs-assessment.html')
MAPPING  = os.path.join(ROOT, 'data', 'hna', 'hna-views.json')
BANNER   = '<!-- GENERATED by scripts/hna/build_hna_views.py from housing-needs-assessment.html — do not edit by hand -->'


def heading_spans(src):
    """Every <h2> with the enclosing container it lives in, in document order."""
    out = []
    for m in re.finditer(r'<h2[^>]*>(.*?)</h2>', src, re.S):
        clean = re.sub(r'<(button|span|details)\b[^>]*class="[^"]*(method|tooltip|tt)[^"]*"[^>]*>.*?</\1>',
                       '', m.group(1), flags=re.S | re.I)
        title = ' '.join(htmllib.unescape(re.sub(r'<[^>]+>', '', clean)).split())
        if not title:
            continue
        si, di = src.rfind('<section', 0, m.start()), src.rfind('<div', 0, m.start())
        start, tag = (si, 'section') if si > di and si >= 0 else (di, 'div')

        # Nearest-opening-tag alone picks the wrong unit. Most of this page is
        # one <section> holding a grid of <div class="chart-card">s, each with
        # its own <h2> -- there the div IS the section. But seven headings own
        # their <section> outright and still have an inner div in front of the
        # h2; removing only that div left the wrapper, the intro prose and the
        # element ids behind -- 1,753 chars of 'Affordable Ownership Need'
        # survived on views that declared it removed, and the renderer happily
        # wrote into the container it found. Prefer the <section> whenever it
        # contains exactly one <h2>.
        # rfind finds the last <section> OPENED before the h2, which may have
        # already closed again -- 'Methodology & Data Sources' is a bare div
        # after </section>, and without the containment test it would adopt the
        # preceding Action Plan section wholesale.
        if tag == 'div' and si >= 0:
            sect = balanced(src, si, 'section')
            if (sect and sect[0] < m.start() < sect[1]
                    and sum(1 for h in re.finditer(r'<h2[^>]*>', src)
                            if sect[0] < h.start() < sect[1]) == 1):
                start, tag = si, 'section'

        span = balanced(src, start, tag)
        if span:
            out.append({'title': title, 'start': span[0], 'end': span[1]})
    return out


def balanced(src, open_idx, tagname):
    depth = 0
    for m in re.finditer(r'<(/?)' + tagname + r'\b[^>]*?(/?)>', src[open_idx:]):
        t = m.group(0)
        if t.startswith('</'):
            depth -= 1
        elif not t.endswith('/>'):
            depth += 1
        if depth == 0:
            return open_idx, open_idx + m.end()
    return None


def matches(title, wanted):
    return title.lower().startswith(wanted.lower()[:44])


def encloses(a, b):
    return a is not b and b['start'] >= a['start'] and b['end'] <= a['end']


def build_view(src, spans, keep_titles, view, all_views):
    """Canonical page minus every section this view does not answer.

    The page is NOT flat: five sections enclose twelve others ('20-year
    outlook' contains 'Population: DOLA forecast' and 'Housing need summary';
    'Labor Market Context' contains three wage sections; and so on). Dropping a
    parent removes its children with it, so a child assigned to a view whose
    parent is not there vanishes from the output WITHOUT appearing in the
    removal comments -- silently, which is the worst way to lose a section.
    Refuse rather than guess: a child must travel with its parent.
    """
    keep = [s for s in spans if any(matches(s['title'], k) for k in keep_titles)]
    drop = [s for s in spans if not any(matches(s['title'], k) for k in keep_titles)]

    orphans = [(k['title'], d['title']) for k in keep for d in drop if encloses(d, k)]
    if orphans:
        print(f"  view '{view['id']}' keeps a section whose PARENT it drops:", file=sys.stderr)
        for child, parent in orphans:
            print(f"     '{child[:52]}'", file=sys.stderr)
            print(f"        is nested inside '{parent[:52]}'", file=sys.stderr)
        print("  A child cannot be split from its parent. Assign the parent to this "
              "view too, or leave the child with it.", file=sys.stderr)
        raise SystemExit(2)
    # outermost-first, then remove back-to-front so offsets stay valid
    drop.sort(key=lambda s: s['start'])
    merged, out = [], src
    for d in drop:
        if merged and d['start'] < merged[-1]['end']:
            continue
        merged.append(d)
    for d in sorted(merged, key=lambda s: -s['start']):
        out = out[:d['start']] + f"\n<!-- [hna-view:{view['id']}] not on this view: {d['title'][:60]} -->\n" + out[d['end']:]
    out = out.replace('<!doctype html>', '<!doctype html>\n' + BANNER, 1)
    return reframe(retitle(out, view), view, all_views)


def retitle(out, view):
    """Give each view its own <title> and description.

    Inherited verbatim from the canonical page, all five views would be called
    'Housing Needs Assessment' -- identical browser tabs, identical bookmarks,
    identical history entries, and five near-duplicate pages for a crawler to
    choose between. Assert one substitution each: a template change that moved
    these tags would otherwise silently ship five identically-named pages.
    """
    title = htmllib.escape(f"{view['nav']} \u2014 Housing Needs Assessment | COHO Analytics")
    desc = htmllib.escape(
        f"{view['question']} Colorado Housing Needs Assessment, built from public "
        "data for a single jurisdiction."
    )
    out, n = re.subn(r'<title>.*?</title>', f'<title>{title}</title>', out, count=1, flags=re.S)
    if n != 1:
        raise SystemExit(f"  view '{view['id']}': no <title> to rewrite")
    out, n = re.subn(r'(<meta\s+name="description"\s+content=")[^"]*(")',
                     lambda m: m.group(1) + desc + m.group(2), out, count=1)
    if n != 1:
        raise SystemExit(f"  view '{view['id']}': no meta description to rewrite")
    return out


def reframe(out, view, all_views):
    """Say on the page which view this is, and offer the other four.

    The canonical <h1> is inherited by all five views, so without this a reader
    who arrives from search sees a page headed 'Housing Needs Assessment' with
    11 of the 53 sections and no indication that the rest exist elsewhere. The
    switcher is plain links, not script: these pages are also printed and
    exported, and a reader following a printed copy needs the slugs visible in
    the markup rather than assembled at runtime.
    """
    n = len(all_views)
    i = next(k for k, v in enumerate(all_views) if v['id'] == view['id'])
    links = ''.join(
        (f'<span class="hna-view-tab is-current" aria-current="page">{htmllib.escape(v["nav"])}</span>'
         if v['id'] == view['id'] else
         f'<a class="hna-view-tab" href="{v["slug"]}">{htmllib.escape(v["nav"])}</a>')
        for v in all_views)
    switcher = (
        '<nav class="hna-view-switcher" aria-label="Housing needs assessment sections">'
        f'{links}'
        '<a class="hna-view-tab hna-view-all" href="housing-needs-assessment.html">'
        'Full report \u2192</a></nav>'
    )
    head = (
        f'<p class="hna-view-step">Housing Needs Assessment \u00b7 part {i + 1} of {n}</p>\n'
        f'<h1>{htmllib.escape(view["nav"])}</h1>\n'
        f'{switcher}'
    )
    out, k = re.subn(r'<h1>Housing Needs Assessment</h1>', head, out, count=1)
    if k != 1:
        raise SystemExit(f"  view '{view['id']}': no canonical <h1> to reframe")

    # The canonical lede describes the whole report; replace it with this
    # view's question so the first sentence matches the sections below it.
    lede = (f'<p class="sub" style="margin-bottom:var(--sp3);">{htmllib.escape(view["question"])} '
            'Built from cached public datasets (Census, DOLA, HUD) with live Census API fallbacks.</p>')
    out, k = re.subn(r'<p class="sub" style="margin-bottom:var\(--sp3\);">.*?</p>',
                     lambda m: lede, out, count=1, flags=re.S)
    if k != 1:
        raise SystemExit(f"  view '{view['id']}': no canonical lede to reframe")
    return out


def prune_assets(pages, canonical_src, rules):
    """Drop files a view cannot use.

    Every view inherits the canonical page's full script list -- 97 tags, 2.26
    MB -- including 183 KB of Leaflet for four views that have no map element
    to draw into. A rule names an element id and the files that only matter
    when it is present.

    This is only safe because the consumers guard on `window.L` rather than
    assuming it; verify that before adding a rule, and re-verify when the
    guards move. Returns a list of problems, empty when clean.
    """
    problems = []
    for rule in rules:
        for path in rule['files']:
            # A typo'd path would silently prune nothing at all.
            if f'"{path}"' not in canonical_src:
                problems.append(f"assets rule lists {path}, which the canonical page does not load")
    if problems:
        return problems

    for slug, html in pages.items():
        dropped = []
        for rule in rules:
            if f'id="{rule["needs_id"]}"' in html:
                continue
            for path in rule['files']:
                before = html
                html = re.sub(
                    r'[ \t]*<(?:script|link)[^>]*"' + re.escape(path) + r'"[^>]*>(?:</script>)?\n?',
                    '', html)
                if html != before:
                    dropped.append(path)
        if dropped:
            note = ', '.join(sorted(dropped))
            html = html.replace('</head>', f'<!-- [hna-view] not loaded here: {note} -->\n</head>', 1)
        pages[slug] = html
    return []


def relink_anchors(pages, canonical_src, labels, idents):
    """Point same-page anchors at the view that actually holds the target.

    The executive decision strip, the section rail and several inline "see
    below" links are all `href="#id"`. They are on every view, but the ids they
    point at are not: four of the five views shipped a 'Need severity' tile and
    a '20-yr production need' tile whose targets live only on 'what to do', so
    clicking them did nothing at all -- no error, no movement, no sign that the
    section exists elsewhere. Rewrite those to the owning view.
    """
    ids = {slug: set(re.findall(r'\bid="([^"]+)"', html)) for slug, html in pages.items()}
    canonical_ids = set(re.findall(r'\bid="([^"]+)"', canonical_src))
    unresolved = []

    for slug, html in pages.items():
        moved = {}

        def fix(m):
            target = m.group(1)
            if target in ids[slug]:
                return m.group(0)
            owner = next((s for s in pages if target in ids[s]), None)
            if owner is None:
                # Still reachable on the full report, which keeps every section.
                if target in canonical_ids:
                    moved[target] = {'page': os.path.basename(SOURCE), 'label': 'the full report'}
                    return f'href="{os.path.basename(SOURCE)}#{target}"'
                unresolved.append((slug, target))
                return m.group(0)
            moved[target] = {'page': owner, 'label': labels[owner]}
            return f'href="{owner}#{target}"'
        html = re.sub(r'href="#([^"]+)"', fix, html)

        # Some of these anchors are re-set from JS at paint time (the executive
        # decision tiles take their href from a constant in hna-renderers.js),
        # so rewriting the markup alone is not enough -- the renderer needs the
        # same mapping at runtime. The canonical page emits none of this and
        # behaves exactly as before.
        anchors = json.dumps(moved, sort_keys=True)
        # Identity for anything that has to name the report: the exporters give
        # every download its own filename and cover line from this.
        ident = json.dumps(idents[slug], sort_keys=True)
        for blob in (anchors, ident):
            assert '</script' not in blob, 'view metadata would close its own script tag'
        pages[slug] = html.replace(
            '</head>',
            f'<script>window.HNA_VIEW={ident};'
            f'window.HNA_VIEW_ANCHORS={anchors};</script>\n</head>', 1)

    if unresolved:
        print('  anchor points at an id no page defines:', file=sys.stderr)
        for slug, target in unresolved:
            print(f"     {slug} -> #{target}", file=sys.stderr)
        return False
    return True


def assert_no_leftovers(pages, src, spans, kept_titles_by_slug):
    """A dropped section must take its element ids with it.

    Deliberately derived from the <section> wrapper in the source, NOT from the
    spans this script computes — a guard that reuses the removal logic can only
    confirm that logic agrees with itself. The first version of this check did
    exactly that and passed against the bug it was written for.

    The bug: removing an inner <div> instead of the <section> around it left the
    wrapper, the intro prose and the element ids behind. Renderers key on ids,
    so a view that declared 'Affordable Ownership Need' removed still computed
    and displayed ownership figures in a container the reader never saw.
    Nothing threw; the page simply reported a section it did not have.
    """
    problems = []
    for sp in spans:
        h2 = src.find('<h2', sp['start'])
        si = src.rfind('<section', 0, h2 if h2 != -1 else sp['start'])
        if si < 0:
            continue
        sect = balanced(src, si, 'section')
        # Only sections that wrap this heading alone: elsewhere the page packs
        # many <h2> cards into one <section>, where the card is the right unit.
        if not sect or not (sect[0] < sp['start'] and sp['end'] <= sect[1]):
            continue
        if sum(1 for h in re.finditer(r'<h2[^>]*>', src) if sect[0] < h.start() < sect[1]) != 1:
            continue
        inside = set(re.findall(r'\bid="([^"]+)"', src[sect[0]:sect[1]]))
        outside = set(re.findall(r'\bid="([^"]+)"', src[:sect[0]] + src[sect[1]:]))
        owned = inside - outside
        for slug, page in pages.items():
            if any(matches(sp['title'], k) for k in kept_titles_by_slug[slug]):
                continue
            for orphan in sorted(owned):
                if f'id="{orphan}"' in page:
                    problems.append(
                        f"{slug} drops '{sp['title'][:42]}' but still carries its "
                        f'id="{orphan}" — renderers will write into it')
    return problems


def audit_shipped(views):
    """Guards that a regenerate alone would not catch.

    The decision tiles take their href from a constant in hna-renderers.js and
    re-set it at paint time, so a view can ship with clean markup and still
    produce dead clicks if that renderer stops consulting the map. Check both
    ends: no dead anchor in the HTML, and the renderer still reads the global.
    """
    problems = []
    for v in views:
        path = os.path.join(ROOT, v['slug'])
        if not os.path.exists(path):
            continue
        html = open(path, encoding='utf-8').read()
        ids = set(re.findall(r'\bid="([^"]+)"', html))
        dead = sorted(t for t in set(re.findall(r'href="#([^"]+)"', html)) if t not in ids)
        for t in dead:
            problems.append(f"{v['slug']} links to #{t}, which nothing on that page defines")

    renderer = os.path.join(ROOT, 'js', 'hna', 'hna-renderers.js')
    if os.path.exists(renderer):
        js = open(renderer, encoding='utf-8').read()
        if 'HNA_VIEW_ANCHORS' not in js:
            problems.append('hna-renderers.js no longer reads window.HNA_VIEW_ANCHORS; '
                            'the decision tiles will be dead clicks on every view')

    exporter = os.path.join(ROOT, 'js', 'hna', 'hna-export.js')
    if os.path.exists(exporter):
        js = open(exporter, encoding='utf-8').read()
        if 'HNA_VIEW' not in js:
            problems.append('hna-export.js no longer reads window.HNA_VIEW; every view '
                            'would export housing-needs-assessment.* with a full-report cover')
    return problems


def main():
    check = '--check' in sys.argv
    if not os.path.exists(SOURCE) or not os.path.exists(MAPPING):
        print('missing source page or mapping', file=sys.stderr)
        return 2
    src = open(SOURCE, encoding='utf-8').read()
    mapping = json.load(open(MAPPING, encoding='utf-8'))
    spans = heading_spans(src)

    shared = [s['title'] for s in mapping['shared']['sections']]
    seen, drift, pages, kept_counts, kept_titles = set(), [], {}, {}, {}
    for v in mapping['views']:
        titles = [s['title'] for s in v['sections']]
        for t in titles + shared:
            if not any(matches(sp['title'], t) for sp in spans):
                print(f"  mapping names a section not on the page: {t!r}", file=sys.stderr)
                return 2
        seen.update(titles)
        pages[v['slug']] = build_view(src, spans, titles + shared, v, mapping['views'])
        kept_counts[v['slug']] = len(titles) + len(shared)
        kept_titles[v['slug']] = titles + shared

    # Every page must exist before this runs: relinking a cross-view anchor
    # means knowing which OTHER view ended up with the target.
    labels = {v['slug']: v['nav'] for v in mapping['views']}
    idents = {v['slug']: {'id': v['id'], 'slug': v['slug'], 'nav': v['nav'],
                          'question': v['question']} for v in mapping['views']}
    asset_problems = prune_assets(pages, src, mapping.get('assets', {}).get('requires', []))
    if asset_problems:
        for line in asset_problems:
            print(f"  {line}", file=sys.stderr)
        return 2

    if not relink_anchors(pages, src, labels, idents):
        return 2

    for v in mapping['views']:
        page = pages[v['slug']]
        dest = os.path.join(ROOT, v['slug'])
        cur = open(dest, encoding='utf-8').read() if os.path.exists(dest) else None
        if check:
            if cur != page:
                drift.append(v['slug'])
        else:
            open(dest, 'w', encoding='utf-8').write(page)
            print(f"  {v['slug']:<44} {kept_counts[v['slug']]:>2} sections  {len(page):>7,} chars")

    unassigned = [sp['title'] for sp in spans
                  if not any(matches(sp['title'], t) for t in list(seen) + shared)]
    if unassigned:
        print(f"  {len(unassigned)} section(s) in no view and not shared:", file=sys.stderr)
        for u in unassigned:
            print(f"     - {u[:66]}", file=sys.stderr)
        return 2

    leftovers = assert_no_leftovers(pages, src, spans, kept_titles)
    if leftovers:
        for line in leftovers:
            print(f"  {line}", file=sys.stderr)
        return 2

    bad = audit_shipped(mapping['views'])
    if bad:
        for line in bad:
            print(f"  {line}", file=sys.stderr)
        return 2

    if check:
        if drift:
            print('STALE — these views differ from a fresh build:')
            for d in drift:
                print(f'   - {d}')
            print('Fix: python3 scripts/hna/build_hna_views.py')
            return 1
        print(f'views are current ({len(mapping["views"])} pages, all {len(spans)} sections accounted for)')
    return 0


if __name__ == '__main__':
    sys.exit(main())
